### ISSUE TITLE
HTTP Server TCK MiscTest fails

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-servlet#375]
### Issue description

https://github.com/micronaut-projects/micronaut-servlet/blob/3.4.x/test-suite-http-server-tck-jetty/src/test/java/io/micronaut/http/server/tck/jetty/tests/JettytHttpServerTestSuite.java#L11

**Comment by timyates** [comment]
So the error is

```
Cannot convert type [class io.micronaut.core.convert.value.ConvertibleValuesMap] to target type: class io.micronaut.http.server.tck.tests.MiscTest$MessageCreate. Considering defining a TypeConverter bean to handle this case.
```

**Comment by yawkat** [comment]
the problem is that there is first a call getBody(ConvertibleValues) and then a second call getBody(MessageCreate). the netty request implementation has the body value fixed as JsonNode from the content type, and converts to either type as necessary. but jetty does not convert to JsonNode it converts directly to ConvertibleValues, and then fails.

There is some existing logic here that does convert to JsonNode, which i guess is used for `@Body`. you could try duplicating this: https://github.com/micronaut-projects/micronaut-servlet/blob/7ec3955a79320259825969162725a0dee2696a5b/servlet-engine/src/main/java/io/micronaut/servlet/engine/bind/DefaultServletBinderRegistry.java#L130

**Comment by timyates** [comment]
@yawkat It already does similar here doesn't it?

https://github.com/micronaut-projects/micronaut-servlet/blob/4b3e4a2e8fe0ace1e0ca7fdaea9d16125fab1f8d/servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpRequest.java#L185

Netty seems to return Optional.empty for the first call, but then a `MessageCreate` object for the second call...

**Comment by timyates** [comment]
When the body annotation is missing, it never seems to get to the `DefaultServletBodyBinder`... trying to work out why

**Comment by yawkat** [comment]
yea it's possible that the JsonObject->ConvertibleValues conversion fails, maybe mimicking that will be enough.

Without a body it goes through ParameterAnnotationBinder, which falls back on using the body, which is correct

**Comment by timyates** [comment]
It seems to successfully create a `ConvertibleValuesMap` and returns it here

https://github.com/micronaut-projects/micronaut-servlet/blob/4b3e4a2e8fe0ace1e0ca7fdaea9d16125fab1f8d/servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpRequest.java#L191

But then we get `Cannot convert type [class io.micronaut.core.convert.value.ConvertibleValuesMap] to target type: class io.micronaut.http.server.tck.tests.MiscTest$MessageCreate. Considering defining a TypeConverter bean to handle this case.`

If I wrap the return value in another map with the argument name `messageCreate` then it works, but this is obviously a hack 🤔

**Comment by yawkat** [comment]
the point is that it should not try to convert from ConvertibleValues to MessageCreate at all, it should go directly from the original body type (in netty this is JsonNode) to MessageCreate
